# Generated by Django 5.2.16 on 2026-07-31 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='código')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('ticket_type', models.CharField(choices=[('incident', 'Incidente'), ('request', 'Solicitud')], default='incident', max_length=20, verbose_name='tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('assigned', 'Asignado'), ('in_progress', 'En progreso'), ('pending', 'Pendiente'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='estado')),
                ('diagnosis', models.TextField(blank=True, verbose_name='diagnóstico')),
                ('root_cause', models.TextField(blank=True, verbose_name='causa raíz')),
                ('resolution', models.TextField(blank=True, verbose_name='resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('due_at', models.DateTimeField(editable=False, verbose_name='vencimiento SLA')),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='resuelto')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='cerrado')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assets.asset', verbose_name='activo afectado')),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category', verbose_name='categoría')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('comment', 'Comentario'), ('status_change', 'Cambio de estado'), ('assignment', 'Asignación'), ('diagnosis', 'Diagnóstico')], default='comment', max_length=20, verbose_name='tipo')),
                ('message', models.TextField(verbose_name='detalle')),
                ('old_value', models.CharField(blank=True, max_length=120, verbose_name='valor anterior')),
                ('new_value', models.CharField(blank=True, max_length=120, verbose_name='valor nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_activities', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['due_at'], name='tickets_tic_due_at_b8e2ab_idx'),
        ),
    ]
