# Generated by Django 5.2.16 on 2026-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketactivity',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='nota interna'),
        ),
    ]
