# Generated by Django 5.2.16 on 2026-07-31 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('summary', models.TextField(verbose_name='resumen')),
                ('content', models.TextField(verbose_name='contenido')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='tickets.category', verbose_name='categoría')),
                ('related_tickets', models.ManyToManyField(blank=True, related_name='knowledge_articles', to='tickets.ticket', verbose_name='tickets relacionados')),
            ],
            options={
                'verbose_name': 'artículo de conocimiento',
                'verbose_name_plural': 'artículos de conocimiento',
                'ordering': ('title',),
            },
        ),
    ]
