# Generated by Django 5.2.16 on 2026-07-31 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=30, unique=True, verbose_name='código de activo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('asset_type', models.CharField(choices=[('desktop', 'PC de escritorio'), ('laptop', 'Notebook'), ('printer', 'Impresora'), ('network', 'Equipo de red'), ('mobile', 'Dispositivo móvil'), ('other', 'Otro')], default='desktop', max_length=20, verbose_name='tipo')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='número de serie')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('retired', 'Retirado')], default='active', max_length=20, verbose_name='estado')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='ubicación')),
                ('operating_system', models.CharField(blank=True, max_length=120, verbose_name='sistema operativo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ('asset_tag',),
            },
        ),
    ]
